services:
  frontend:
    build: ./meal-tracker-web-app-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      my-network:
        aliases:
        - frontend

  backend:
    build: ./meal-tracker-web-app-backend
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      my-network:
        aliases:
          - backend

  db:
    image: "postgres:13.1-alpine"
    restart: always
    container_name: meal-tracker-web-app-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meal-user
      POSTGRES_PASSWORD: test1234
    volumes:
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meal-user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      my-network:
        aliases:
          - db

networks:
  my-network: